name: ESLint Report

on:
  workflow_run:
    workflows:
      - JavaScript and CSS Linting
    types:
      - completed

jobs:
  JSLintResults:
    name: Annotate Code Linting Results
    uses: ataylorme/eslint-annotate-action@1.2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        report-json: "eslint_report.json"
