on:
    workflow_run:
        workflows: ['Linting']
        types:
            - completed
jobs:
    annotate:
        name: Annotate Code Linting Results
        runs-on: ubuntu-latest
        uses: ataylorme/eslint-annotate-action@1.2.0
        with:
            repo-token: '${{ secrets.GITHUB_TOKEN }}'
            report-json: 'eslint_report.json'
